version: "3.9"

services:
  mongo:
    image: mongo:5.0.2
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "27017:27017"
    volumes:
      - /var/local/mongo-restaurants:/data/db

  backend:
    depends_on:
      - mongo
    links:
      - mongo
    build: ./backend
    restart: unless-stopped
    env_file: ./.env
    ports:
      - 8080:8080
    stdin_open: true
    tty: true

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    links:
      - backend